language: cpp

compiler:
  - gcc

before_script:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq libboost-filesystem-dev libboost-test-dev g++-4.8
  - export CXX="g++-4.8"
  - cmake .
  - make

script: make test